exclude-labels:
  - skip changelog
  - release
name-template: 'Narwhals v$RESOLVED_VERSION'

change-template: '- $TITLE (#$NUMBER)' 
    
autolabeler:
  - label: breaking
    title:
      # Example: feat!: ...
      - '/^([B|b]uild|[C|c]hore|[CI|ci]|[D|d]epr|[D|d]oc|DOC|[F|f]eat|[F|f]ix|[P|p]erf|[R|r]efactor|[R|r]elease|[T|t]est)\! /'
  - label: build
    title:
      - '/^([B|b]uild)/'
  - label: internal
    title:
      - '/^(chore|ci|refactor|test|template|bench|Chore|CI|Refactor|Test|Template|Bench)'
  - label: deprecation
    title:
      - '/^([D|d]epr)/'
  - label: documentation
    title:
      - '/^([D|d]oc|DOC)/'
  - label: enhancement
    title:
      - '/^(feat|enh|Feat|ENH|Enh)/'
  - label: fix
    title:
      - '/^([F|f]ix)/'
  - label: performance
    title:
      - '/^([P|p]erf)/'
  - label: release
    title:
      - '/^([R|r]elease)/'
      
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
  
categories:
  - title: 🏆 Highlights
    labels: highlight
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: ⚠️ Deprecations
    labels: deprecation
  - title: 🚀 Performance improvements
    labels: performance
  - title: ✨ Enhancements
    labels: enhancement
  - title: 🐞 Bug fixes
    labels: fix
  - title: 📖 Documentation
    labels: documentation
  - title: 📦 Build system
    labels: build
  - title: 🛠️ Other improvements
    labels: internal

template: |
  ## Changes

  $CHANGES

  Thank you to all our contributors for making this release possible!
  $CONTRIBUTORS
