blank_issues_enabled: true
contact_links:
- name: Discord server
  url: https://discord.gg/V3PqtB4VA4)
  about: Developers and users can be found on the Discord server
- name: Blank issue
  url: https://github.com/narwhals-dev/narwhals/issues/new
  about: Please note that GitHub Discussions are preferred  