name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mkdocs:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}
      - name: install-reqs
        run: python -m pip install --upgrade tox virtualenv setuptools pip -r requirements-dev.txt
      - name: install-docs-reqs
        run: python -m pip install --upgrade -r docs/requirements-docs.txt
      - name: local-install
        run: python -m pip install -e .
      - name: check-no-errors
        run: python -m mkdocs build > output.txt 2>&1
      - name: assert-no-errors
        run: python utils/check_for_no_build_errors.py
      - name: strict-docs-build
        run: mkdocs build --strict
