name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  altair:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}
      - name: clone-altair
        run: git clone https://github.com/vega/altair.git
      - name: install-basics
        run: python -m pip install --upgrade tox virtualenv setuptools pip
      - name: install-altair-dev
        run: |
            cd altair
            pip install -e ".[dev, all]"
      - name: install-narwhals-dev
        run: |
            pip uninstall narwhals -y
            pip install -e .
      - name: show-deps
        run: pip freeze
      - name: Run pytest
        run: |
            cd altair
            pytest tests
      - name: Run mypy
        run: |
            cd altair
            mypy altair tests

  scikit-lego:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}
      - name: clone-scikit-lego
        run: git clone https://github.com/koaning/scikit-lego.git
      - name: install-basics
        run: python -m pip install --upgrade tox virtualenv setuptools pip
      - name: install-scikit-lego-dev
        run: |
            cd scikit-lego
            pip install -e ".[test]"
      - name: install-narwhals-dev
        run: |
            pip uninstall narwhals -y
            pip install -e .
      - name: show-deps
        run: pip freeze
      - name: Run pytest
        run: |
            cd scikit-lego
            pytest -n auto --disable-warnings --cov=sklego -m "not cvxpy and not formulaic and not umap"
