name: PyTest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest-38:
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: "true"
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: install-reqs
        # Python3.8 is technically at end-of-life, so we don't test everything
        run: uv pip install -e ".[dev, core]" --system
      - name: show-deps
        run: uv pip freeze
      - name: Run pytest
        run: pytest tests --cov=narwhals --cov=tests --cov-fail-under=85 --constructors=pandas,pyarrow,polars[eager],polars[lazy]

  pytest-windows:
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: "true"
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: install-reqs
        run: uv pip install -e ".[dev, core, extra, dask, modin]" --system
      - name: show-deps
        run: uv pip freeze
      - name: Run pytest
        run: |
          pytest tests --cov=narwhals --cov=tests --runslow --cov-fail-under=95 \
          --constructors="pandas,pandas[nullable],pandas[pyarrow],modin,modin[pyarrow],dask,polars[eager],polars[lazy]"

  pytest-full-coverage:
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.13"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: "true"
          cache-suffix: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: install-reqs
        run: uv pip install -e ".[dev, core, extra, modin, dask, pyspark]" --system
      - name: install ibis
        run: uv pip install -e ".[ibis]" --system
        # Ibis puts upper bounds on dependencies, and requires Python3.10+,
        # which messes with other dependencies on lower Python versions
        if: matrix.python-version == '3.11'
      - name: show-deps
        run: uv pip freeze
      - name: Run pytest
        run: pytest tests --cov=narwhals --cov=tests --cov-fail-under=100 --runslow --all-cpu-constructors
      - name: Run doctests
        # reprs differ between versions, so we only run doctests on the latest Python
        if: matrix.python-version == '3.13'
        run: pytest narwhals --doctest-modules
