name: random-versions

on:
  pull_request:

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install package
        run: pip install -e .
      - name: generate-random-versions
        run: python utils/generate_random_versions.py
      - name: install-reqs
        run: python -m pip install --upgrade tox virtualenv setuptools pip && python -m pip install -r requirements-dev.txt
      - name: uninstall scipy/sklearn
        run: python -m pip uninstall -y scipy scikit-learn
      - name: install-random-verions
        run: python -m pip install -r random-requirements.txt
      - name: show versions
        run: python -m pip freeze
      - name: Run pytest
        run: pytest tests --cov=narwhals --cov=tests --cov-fail-under=80
